### ISSUE TITLE
API user constantly disconnect

### ISSUE THREAD

**Issue by 5h4k4** [akpw/mktxp-stack#18]
Hi i am having problems scraping one of my Mikrotik devices, the API user constantly disconnect during rush hour.

![Screenshot from 2024-03-26 12-19-50](https://github.com/akpw/mktxp-stack/assets/76045923/795453fc-c49d-4cbb-8e5a-4638c34f2a06)

_mktxp.conf
```
[MKTXP]
    socket_timeout = 2
    initial_delay_on_failure = 120
    max_delay_on_failure = 900
    delay_inc_div = 5
    bandwidth_test_interval = 420
    minimal_collect_interval = 5
    max_worker_threads = 5
    max_scrape_duration = 10
    total_max_scrape_duration = 30
    fetch_routers_in_parallel = True
    compact_default_conf_values = False
    verbose_mode = False
    bandwidth = False
    listen = 0.0.0.0:49090
```

mktxp.conf
```
[MK]
    netwatch = True
    public_ip = True
    queue = True
    no_ssl_certificate = False
    ssl_certificate_verify = False
    dhcp_lease = False
    ipv6_firewall = False
    monitor = True
    wireless_clients = False
    enabled = True
    kid_control_devices = False
    bgp = False
    connection_stats = False
    capsman_clients = False
    ipv6_neighbor = False
    poe = False
    use_comments_over_names = True
    firewall = True
    user = True
    installed_packages = True
    capsman = False
    check_for_updates = False
    interface = True
    route = True
    use_ssl = False
    connections = True
    dhcp = False
    wireless = False
    pool = False
```

prometheus.yml
```
# global config
global:
  scrape_interval: 45s # Set the scrape interval to every 45 seconds. Default is every 1 minute.
  scrape_timeout: 30s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    origin_prometheus: mktxp

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
    - targets: ['promtail:9080']

  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']
```

Looks like a timeout, maybe it's taking too long to finish the scrap during high usage hours.
What and where should I change? I try `fetch_routers_in_parallel = True` but didn't help

From already thank you very much
