### ISSUE TITLE
How to add a second mikrotik?

### ISSUE THREAD

**Issue by k-szortyka** [akpw/mktxp-stack#2]
How to add a second mikrotik?

**Comment by akpw** [comment]
@k-szortyka it's same approach as for the first one, just redirect additional routers' logs to remote mktxp-stack target

**Comment by k-szortyka** [comment]
@akpw The remote configuration on the second router is the same on the first one.
I duplicated mktxp directory (mktxp2) with changed hostname and I added to prometheus.yml:
```
  - job_name: 'mktxp2'
    static_configs:
      - targets: ['mktxp2:49090']
```
and to docker-compose-mktxp-stack.yml:
```
  mktxp2:
    container_name: mktxp2
    image: ghcr.io/akpw/mktxp:latest
    volumes:
      - './mktxp2/:/home/mktxp/mktxp/'
    restart: unless-stopped
```
but I only see the logs of the second router but I don't see second router in Mikrotik MKTXP Exporter and Prometheus.
