### ISSUE TITLE
NEED TO CHANGE 514 PORT

### ISSUE THREAD

**Issue by Gero6700** [akpw/mktxp-stack#21]
I need to change 514 port where I have to modify this? I add this "syslog(transport(udp) port(8514));"  on syslog-ng/syslog-ng-fs.conf but doesn't work...

**Comment by akpw** [comment]
assuming you are running the FS log version, have you tried just setting the port in the relevant section of the `docker-compose-mktxp-stack-fs.yml`?

```
syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    networks:
      mktxp: null
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: always
    volumes:
    - ./syslog-ng/syslog-ng-fs.conf:/etc/syslog-ng/syslog-ng.conf:ro
    - mktxp-logs:/var/log/syslog-ng
```
