### ISSUE TITLE
Mikrotik Loki Logs not working properly

### ISSUE THREAD

**Issue by derritter88** [akpw/mktxp-stack#30]
The Dashboard shows for "Log Counts By Topic" only "No Data" and also "Log County By Topic over Time" shows only "Data is missing a number field".

Additional Search is also not working.

Logs in general are being displayed

**Comment by akpw** [comment]
@derritter88  which config are you using, default or file-system based? If the latter, have you checked how the logs look like on your file system?

**Comment by derritter88** [comment]
@akpw syslog via syslog-ng-fs.conf

**Comment by akpw** [comment]
OK  so sounds like 
`$ docker compose -f ./docker-compose-mktxp-stack-fs.yml up -d` then.  
Assuming no changes in mktxp-logs volume mapping there, can you do 
```$ ls -l syslog-ng/logs/```
 to check on your actual logs there?

**Comment by derritter88** [comment]
I modified your docker-compose.yml a bit to my needs as I already had some services in place like Grafana.
For documentation purposes here would be me current and working compose.yml:

```yaml
networks:
  mktxp: {}

volumes:
  mktxp-logs:
    driver_opts:
       o: bind
       type: none
       device: $PWD/syslog-ng/logs
  prometheus_storage: {}
  grafana_storage: {}

services:
  mktxp:
    container_name: mktxp
    image: ghcr.io/akpw/mktxp:1.2.10@sha256:919734979cbf3d5b82b50449a0dac94fae3b79b1ee0dcf415bf0023510323f83
    user: root
    environment:
      - TZ=Europe/Vienna
    volumes:
      - './mktxp/:/root/mktxp/'
    networks:
      mktxp: null
    ports:
      - protocol: tcp
        published: 49090
        target: 49090
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:3.4.2@sha256:58a6c186ce78ba04d58bfe2a927eff296ba733a430df09645d56cdc158f3ba08
    environment:
      - TZ=Europe/Vienna
    networks:
      mktxp: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: unless-stopped
    volumes:
    - ./loki/loki-config.yml:/etc/loki/loki-config.yml

  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:3.4.2@sha256:c6e9a987ca086cbfef945b8ebd708eb09f98b5e78bfb659e4e5a8b3bd604d11b
    environment:
      - TZ=Europe/Vienna
    networks:
      mktxp: null
    ports:
    - protocol: tcp
      published: 1514
      target: 1514
    - protocol: tcp
      published: 9080
      target: 9080
    restart: unless-stopped
    volumes:
    - ./promtail/promtail-config-fs.yml:/etc/promtail/promtail-config.yml:ro
    - mktxp-logs:/var/log:ro

  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:4.8.0@sha256:835dec2018cf96ee1d7051950851c07f6f11ba538d89a828e40307a47117c049
    environment:
      - TZ=Europe/Vienna
    networks:
      mktxp: null
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 601
      target: 601
    restart: unless-stopped
    volumes:
    - ./syslog-ng/syslog-ng-fs.conf:/etc/syslog-ng/syslog-ng.conf:ro
    - mktxp-logs:/var/log/syslog-ng
```



Logs in general are being written to the log file and I could count whem via `wc -l`
